---
title: "presentation"
format: html
---

```{r}
library(tidyverse)
library(plotly)
```


# OLS example

```{r}
set.seed(12347)
x <- seq(0, 20, by = 0.25)

y_true <- 2 * x + 20

y_noisy <- y_true + rnorm(length(x), 0, 6)

ols_df <- data.frame(x = x, y = y_noisy)

ols_df |>
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  theme_minimal()
```


```{r}
# fit
ols_fit <- lm(y_noisy ~ x)
b0_hat <- coef(ols_fit)[1]
b1_hat <- coef(ols_fit)[2]

ols_df |>
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(x = x, y = b0_hat + b1_hat * x), color = "#006D77", linewidth = 1.3) +
  theme_minimal()
```


```{r}
# create grid
b0_seq <- seq(b0_hat - 20, b0_hat + 20, length.out = 80)
b1_seq <- seq(b1_hat - 6,  b1_hat + 6,  length.out = 80)

# create sse grid for all combos
sse_matrix <- outer(b0_seq, b1_seq, FUN = function(b0, b1) {
  sapply(seq_along(b0), function(i) {
    residuals <- y_noisy - (b0[i] + b1[i] * x)
    sum(residuals^2)
  })
})

# plot
plot_ly() |>
  add_surface(
    x = b1_seq,
    y = b0_seq,
    z = sse_matrix,
    colorscale = list(c(0, "#2166AC"), c(0.25, "#74C8C0"), c(0.5, "#FFE81A"), c(0.75, "#F98E2B"), c(1, "#D6191B")),
    colorbar = list(title = "SSE"),
    contours = list(
      z = list(
        show      = TRUE,
        start     = 0,
        end       = max(sse_matrix),
        size      = 10000,
        color     = "white",
        width     = 2,
        highlight = FALSE
      ),
      y = list(
        show      = TRUE,
        start     = 0,
        end       = max(sse_matrix),
        size      = 1,
        color     = "white",
        width     = 5,
        highlight = FALSE
      )
    )) |>
  add_markers(
    x = b1_hat,
    y = b0_hat,
    z = sum(residuals(ols_fit)^2),
    marker = list(color = "red", size = 6, symbol = "circle"),
    name = "OLS minimum") |>
  layout(
    scene = list(
      xaxis = list(title = "β₁"),
      yaxis = list(title = "β₀"),
      zaxis = list(title = "SSE"),
      camera = list(eye = list(x = 1.5, y = -1.8, z = 0.8))),
    title = list(text = "SSE solution space", x = 0.05))
```






